# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Katydid'
tagline:          'Tree Grammars for Trees'
url:              "http://katydid.github.io/v0.1"
baseurl:          "/v0.1"

author:
  name:           'Walter Schulze'
  url:            https://plus.google.com/u/0/+WalterSchulzeA

paginate:         5

# Custom vars
version:          Deprecated

github:
  repo:           https://github.com/katydid/v0.1

gems:
  - jekyll-sitemap

